# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3902f6276c881c2f94241e80ec27cd41"
name = "SpinoramaBilling"
handle = "spinoramabilling"
application_url = "https://expertise-presenting-alfred-intermediate.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "win-to-spin.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://expertise-presenting-alfred-intermediate.trycloudflare.com/auth/callback",
  "https://expertise-presenting-alfred-intermediate.trycloudflare.com/auth/shopify/callback",
  "https://expertise-presenting-alfred-intermediate.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-04"

[pos]
embedded = false
