# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "aa7f6258a74870e804dc2246dc4b683d"
name = "spin-to-win"
handle = "spin-to-win-10"
application_url = "https://graduate-ranked-like-delivery.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "win-to-spin.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_orders,write_products"

[auth]
redirect_urls = [
  "https://graduate-ranked-like-delivery.trycloudflare.com/auth/callback",
  "https://graduate-ranked-like-delivery.trycloudflare.com/auth/shopify/callback",
  "https://graduate-ranked-like-delivery.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-01"

[pos]
embedded = false
