# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "cc449da5fb0ceb886cd028d46d817acc"
name = "spin-factory"
handle = "spin-factory"
application_url = "https://freeware-futures-ready-portland.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "win-to-spin.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://freeware-futures-ready-portland.trycloudflare.com/auth/callback",
  "https://freeware-futures-ready-portland.trycloudflare.com/auth/shopify/callback",
  "https://freeware-futures-ready-portland.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-04"

[pos]
embedded = false
