# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b1af4757b31fe702a75c6c21aaedd75c"
name = "Spinorama"
handle = "spinorama"
application_url = "https://seal-app-2smk6.ondigitalocean.app/"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_discounts,read_products,write_discounts,write_products"

[auth]
redirect_urls = [
  "https://seal-app-2smk6.ondigitalocean.app/auth/callback",
  "https://seal-app-2smk6.ondigitalocean.app/auth/shopify/callback",
  "https://seal-app-2smk6.ondigitalocean.app/api/auth/callback"
]

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  uri = "CUSTOMERS_DATA_REQUEST"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "CUSTOMERS_REDACT"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "SHOP_REDACT"
  compliance_topics = [ "shop/redact" ]

[pos]
embedded = false
