# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b65f81836db5bb58616b381a853305dd"
name = "spin-to-win"
handle = "spin-to-win-8"
application_url = "https://victoria-heavy-century-tampa.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "twistwin.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://victoria-heavy-century-tampa.trycloudflare.com/auth/callback",
  "https://victoria-heavy-century-tampa.trycloudflare.com/auth/shopify/callback",
  "https://victoria-heavy-century-tampa.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2025-01"

[pos]
embedded = false
